In [16]:
import pandas as pd 
import numpy as np

In [4]:
df=pd.read_csv("IPL2025Batters.csv")
print("Success")

Success

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Player Name  156 non-null    object
 1   Team         156 non-null    object
 2   Runs         156 non-null    int64
 3   Matches      156 non-null    int64
 4   Inn          156 non-null    int64
 5   No           156 non-null    int64
 6   HS           156 non-null    object
 7   AVG          156 non-null    object
 8   BF           156 non-null    int64
 9   SR           156 non-null    float64
 10  100s         156 non-null    int64
 11  50s          156 non-null    int64
 12  4s           156 non-null    int64
 13  6s           156 non-null    int64
dtypes: float64(1), int64(9), object(4)
memory usage: 17.2+ KB

In [4]:
df.isnull().sum()

Player Name    0
Team           0
Runs           0
Matches        0
Inn            0
No             0
HS             0
AVG            0
BF             0
SR             0
100s           0
50s            0
4s             0
6s             0
dtype: int64

In [5]:
df.isnull().sum().sum()

np.int64(0)

In [7]:
df.head(10)

,Player Name,Team,Runs,Matches,Inn,No,HS,AVG,BF,SR,100s,50s,4s,6s
0,Sai Sudharsan,GT,759,15,15,1,108*,54.21,486,156.17,1,6,88,21
1,Surya Kumar Yadav,MI,717,16,16,5,73*,65.18,427,167.91,0,5,69,38
2,Virat Kohli,RCB,657,15,15,3,73*,54.75,454,144.71,0,8,66,19
3,Shubman Gill,GT,650,15,15,2,93*,50.00,417,155.87,0,6,62,24
4,Mitchell Marsh,LSG,627,13,13,0,117,48.23,383,163.70,1,6,56,37
5,Shreyas Iyer,PBKS,604,17,17,5,97*,50.33,345,175.07,0,6,43,39
6,Yashasvi Jaiswal,RR,559,14,14,1,75,43.00,350,159.71,0,6,60,28
7,Prabhsimran Singh,PBKS,549,17,17,0,91,32.29,342,160.52,0,4,56,30
8,K L Rahul,DC,539,13,13,3,112*,53.90,360,149.72,1,3,52,21
9,Jos Buttler,GT,538,14,13,4,97*,59.78,330,163.03,0,5,52,24

In [7]:
df.tail(10)

,Player Name,Team,Runs,Matches,Inn,No,HS,AVG,BF,SR,100s,50s,4s,6s
146,Spencer Johnson,KKR,2,4,2,2,1*,-,4,50.00,0,0,0,0
147,Arshdeep Singh,PBKS,2,17,2,1,1*,2.00,6,33.33,0,0,0,0
148,Varun Chakaravarthy,KKR,1,13,1,1,1*,-,1,100.00,0,0,0,0
149,V Satyanarayana Penmetsa,MI,1,2,1,1,1*,-,1,100.00,0,0,0,0
150,Karn Sharma,MI,1,6,1,1,1*,-,1,100.00,0,0,0,0
151,Khaleel Ahmed,CSK,1,14,2,2,1*,-,2,50.00,0,0,0,0
152,Mohit Sharma,DC,1,8,2,1,1*,1.00,3,33.33,0,0,0,0
153,Donovan Ferreira,DC,1,1,1,0,1,1.00,3,33.33,0,0,0,0
154,Digvesh Singh,LSG,1,13,2,1,1,1.00,3,33.33,0,0,0,0
155,Manoj Bhandage,RCB,1,1,1,0,1,1.00,4,25.00,0,0,0,0

In [6]:
df.describe()

,Runs,Matches,Inn,No,BF,SR,100s,50s,4s,6s
count,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000
mean,161.320513,9.865385,7.153846,1.634615,105.673077,134.394103,0.057692,0.916667,14.391026,8.294872
std,180.352772,4.757455,4.810142,1.658163,112.191838,57.237148,0.233912,1.590124,17.778774,9.515500
min,1.000000,1.000000,1.000000,0.000000,1.000000,25.000000,0.000000,0.000000,0.000000,0.000000
25%,10.750000,6.000000,2.750000,0.000000,12.000000,100.000000,0.000000,0.000000,1.000000,0.000000
50%,93.500000,11.000000,6.000000,1.000000,63.500000,140.005000,0.000000,0.000000,7.000000,4.000000
75%,254.250000,14.000000,12.000000,3.000000,164.750000,162.707500,0.000000,1.000000,23.000000,14.000000
max,759.000000,17.000000,17.000000,7.000000,486.000000,400.000000,1.000000,8.000000,88.000000,40.000000

In [9]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
151    False
152    False
153    False
154    False
155    False
Length: 156, dtype: bool

In [12]:
print(df["AVG"].unique())

['54.21' '65.18' '54.75' '50.00' '48.23' '50.33' '43.00' '32.29' '53.90'
 '59.78' '43.67' '44.27' '27.94' '34.23' '33.77' '29.86' '33.58' '32.75'
 '35.45' '29.85' '31.17' '30.75' '32.45' '35.40' '31.18' '37.00' '32.90'
 '24.00' '25.08' '33.44' '33.33' '32.33' '35.63' '30.89' '24.45' '26.30'
 '37.29' '36.00' '31.50' '27.44' '22.36' '34.29' '21.73' '26.22' '23.30'
 '37.50' '24.89' '21.70' '29.43' '29.14' '22.44' '24.75' '24.50' '27.29'
 '62.33' '22.75' '29.83' '18.56' '20.50' '26.67' '26.00' '30.60' '21.71'
 '20.29' '26.60' '24.40' '40.33' '39.33' '22.80' '16.00' '18.17' '26.50'
 '12.38' '24.25' '31.67' '46.00' '30.67' '42.50' '18.75' '18.50' '14.20'
 '35.00' '22.67' '33.50' '10.50' '12.20' '14.25' '9.17' '11.00' '8.00'
 '23.50' '9.40' '20.00' '8.25' '6.20' '11.50' '22.00' '21.00' '6.00'
 '8.50' '-' '7.00' '14.00' '4.67' '13.00' '6.50' '10.00' '5.00' '9.00'
 '1.80' '2.33' '1.75' '3.00' '1.67' '2.50' '2.00' '1.50' '1.00']

In [13]:
df["AVG"].value_counts()

AVG
-        15
1.00      4
9.00      3
11.00     3
50.00     3
         ..
6.50      1
1.67      1
1.75      1
2.33      1
2.50      1
Name: count, Length: 118, dtype: int64

In [14]:
df[df["AVG"] == "-"]

,Player Name,Team,Runs,Matches,Inn,No,HS,AVG,BF,SR,100s,50s,4s,6s
109,Jamie Overton,CSK,15,3,2,2,11*,-,7,214.28,0,0,1,1
118,Dushmantha Chameera,DC,10,6,3,3,8*,-,14,71.42,0,0,0,0
124,Kwena Maphaka,RR,8,2,1,1,8*,-,2,400.00,0,0,2,0
125,Raj Angad Bawa,MI,8,3,1,1,8*,-,4,200.00,0,0,0,0
130,Sandeep Sharma,RR,6,10,1,1,6*,-,5,120.00,0,0,0,0
135,Prince Yadav,LSG,5,6,2,2,4*,-,10,50.00,0,0,0,0
137,Lockie Ferguson,PBKS,4,4,1,1,4*,-,1,400.00,0,0,1,0
139,Akash Madhwal,RR,4,4,1,1,4*,-,9,44.44,0,0,0,0
141,Mohammed Siraj,GT,3,15,1,1,3*,-,4,75.00,0,0,0,0
144,Fazalhaq Farooqi,RR,2,5,1,1,2*,-,2,100.00,0,0,0,0
146,Spencer Johnson,KKR,2,4,2,2,1*,-,4,50.00,0,0,0,0
148,Varun Chakaravarthy,KKR,1,13,1,1,1*,-,1,100.00,0,0,0,0
149,V Satyanarayana Penmetsa,MI,1,2,1,1,1*,-,1,100.00,0,0,0,0
150,Karn Sharma,MI,1,6,1,1,1*,-,1,100.00,0,0,0,0
151,Khaleel Ahmed,CSK,1,14,2,2,1*,-,2,50.00,0,0,0,0

In [17]:
df["AVG"] = df["AVG"].replace("-", np.nan)

In [18]:
df[df["AVG"] == "-"]

Empty DataFrame
Columns: [Player Name, Team, Runs, Matches, Inn, No, HS, AVG, BF, SR, 100s, 50s, 4s, 6s]
Index: []

In [19]:
df["AVG"].value_counts()

AVG
1.00     4
9.00     3
3.00     3
6.00     3
50.00    3
        ..
6.50     1
1.67     1
1.75     1
2.33     1
2.50     1
Name: count, Length: 117, dtype: int64

In [20]:
df.tail(10)

,Player Name,Team,Runs,Matches,Inn,No,HS,AVG,BF,SR,100s,50s,4s,6s
146,Spencer Johnson,KKR,2,4,2,2,1*,NaN,4,50.00,0,0,0,0
147,Arshdeep Singh,PBKS,2,17,2,1,1*,2.00,6,33.33,0,0,0,0
148,Varun Chakaravarthy,KKR,1,13,1,1,1*,NaN,1,100.00,0,0,0,0
149,V Satyanarayana Penmetsa,MI,1,2,1,1,1*,NaN,1,100.00,0,0,0,0
150,Karn Sharma,MI,1,6,1,1,1*,NaN,1,100.00,0,0,0,0
151,Khaleel Ahmed,CSK,1,14,2,2,1*,NaN,2,50.00,0,0,0,0
152,Mohit Sharma,DC,1,8,2,1,1*,1.00,3,33.33,0,0,0,0
153,Donovan Ferreira,DC,1,1,1,0,1,1.00,3,33.33,0,0,0,0
154,Digvesh Singh,LSG,1,13,2,1,1,1.00,3,33.33,0,0,0,0
155,Manoj Bhandage,RCB,1,1,1,0,1,1.00,4,25.00,0,0,0,0

In [22]:
df["Runs"]=pd.to_numeric(df["Runs"],errors="coerce")

In [ ]:
df[""]=pd.to_numeric(df["Runs"],errors="coerce")

In [24]:
df["AVG"]=df["AVG"].fillna(df["Runs"] / df["Matches"])

In [27]:
df.tail(10)

,Player Name,Team,Runs,Matches,Inn,No,HS,AVG,BF,SR,100s,50s,4s,6s
146,Spencer Johnson,KKR,2,4,2,2,1*,0.5,4,50.00,0,0,0,0
147,Arshdeep Singh,PBKS,2,17,2,1,1*,2.00,6,33.33,0,0,0,0
148,Varun Chakaravarthy,KKR,1,13,1,1,1*,0.076923,1,100.00,0,0,0,0
149,V Satyanarayana Penmetsa,MI,1,2,1,1,1*,0.5,1,100.00,0,0,0,0
150,Karn Sharma,MI,1,6,1,1,1*,0.166667,1,100.00,0,0,0,0
151,Khaleel Ahmed,CSK,1,14,2,2,1*,0.071429,2,50.00,0,0,0,0
152,Mohit Sharma,DC,1,8,2,1,1*,1.00,3,33.33,0,0,0,0
153,Donovan Ferreira,DC,1,1,1,0,1,1.00,3,33.33,0,0,0,0
154,Digvesh Singh,LSG,1,13,2,1,1,1.00,3,33.33,0,0,0,0
155,Manoj Bhandage,RCB,1,1,1,0,1,1.00,4,25.00,0,0,0,0

In [28]:
df["HS_NotOut"] = df["HS"].str.contains(r"\*").astype(int)

df["HS"] = df["HS"].str.replace("*", "", regex=False)
df["HS"] = pd.to_numeric(df["HS"], errors="coerce")

In [31]:
df.head()

,Player Name,Team,Runs,Matches,Inn,No,HS,AVG,BF,SR,100s,50s,4s,6s,HS_NotOut
0,Sai Sudharsan,GT,759,15,15,1,108,54.21,486,156.17,1,6,88,21,1
1,Surya Kumar Yadav,MI,717,16,16,5,73,65.18,427,167.91,0,5,69,38,1
2,Virat Kohli,RCB,657,15,15,3,73,54.75,454,144.71,0,8,66,19,1
3,Shubman Gill,GT,650,15,15,2,93,50.00,417,155.87,0,6,62,24,1
4,Mitchell Marsh,LSG,627,13,13,0,117,48.23,383,163.70,1,6,56,37,0

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Player Name  156 non-null    object
 1   Team         156 non-null    object
 2   Runs         156 non-null    int64
 3   Matches      156 non-null    int64
 4   Inn          156 non-null    int64
 5   No           156 non-null    int64
 6   HS           156 non-null    int64
 7   AVG          156 non-null    float64
 8   BF           156 non-null    int64
 9   SR           156 non-null    float64
 10  100s         156 non-null    int64
 11  50s          156 non-null    int64
 12  4s           156 non-null    int64
 13  6s           156 non-null    int64
 14  HS_NotOut    156 non-null    int64
dtypes: float64(2), int64(11), object(2)
memory usage: 18.4+ KB

In [34]:
df["AVG"]=pd.to_numeric(df["AVG"],errors="coerce")

In [36]:
X = df[["Matches","Inn","No","HS","BF","SR","100s","50s","4s","6s"]]

y = df["Runs"]

In [42]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [38]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [43]:
model = LinearRegression()

In [44]:
model.fit(X_train, y_train)

LinearRegression()

In [45]:
y_pred = model.predict(X_test)

In [47]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

print("MAE:", mean_absolute_error(y_test, y_pred))
print("MSE:", mean_squared_error(y_test, y_pred))
print("R2 Score:", r2_score(y_test, y_pred))

MAE: 5.741883342080593
MSE: 59.529166425281495
R2 Score: 0.9976747731243538

In [55]:
virat = df[df["Player Name"] == "Virat Kohli"]

X_new = virat[["Matches","Inn","No","HS","BF","SR","100s","50s","4s","6s"]]

prediction = model.predict(X_new)

print(prediction)

[654.63326613]

In [53]:
virat = df[df["Player Name"] == "Virat"]

In [54]:
print(df["Player Name"])

0          Sai Sudharsan
1      Surya Kumar Yadav
2            Virat Kohli
3           Shubman Gill
4         Mitchell Marsh
             ...
151        Khaleel Ahmed
152         Mohit Sharma
153     Donovan Ferreira
154        Digvesh Singh
155       Manoj Bhandage
Name: Player Name, Length: 156, dtype: object

In [57]:
v = df[df["Player Name"] == "Shubman Gill"]

X_new = v[["Matches","Inn","No","HS","BF","SR","100s","50s","4s","6s"]]

prediction = model.predict(X_new)

print(prediction)

[629.14187545]